name: Continuous Integration

on:
  push:
  schedule:
    - cron: "0 2 * * 1"

jobs:
  prepare:
    runs-on: windows-latest
    steps:
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1

  build_and_test:
    needs: prepare
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Fetch rootsimcc repository
        uses: actions/checkout@v2
      - name: Build & Test
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          cc: clang
          build-type: Debug
          run-test: true
