name: REUSE Compliance Check

on:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkpout repository
        uses: actions/checkout@v2
      - name: REUSE check
        uses: ROOT-Sim/ci-actions/reuse-check@v1
